service: BookingApp

plugins:
  - serverless-appsync-plugin
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions: 
  # Auth controller
  - ${file(resources/functions/authController-function.yml)}

custom:
  # AppSync setup
  appSync:
    name: ${self:service}-api
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: eu-central-1
      defaultAction: ALLOW
      userPoolId: { Ref: CognitoUserPool }
    serviceRole: "cognitoAppServiceRole"
    # Data sources 
    dataSources:
      - ${file(resources/appsync/dataSources/authLambdaFunction.yml)}
    # Mapping templates
    mappingTemplates:
      - ${file(resources/appsync/mappingTemplates/adminLogin.yml)}
      - ${file(resources/appsync/mappingTemplates/adminList.yml)}
      - ${file(resources/appsync/mappingTemplates/adminRegister.yml)}
      - ${file(resources/appsync/mappingTemplates/adminPasswordRecover.yml)}
      - ${file(resources/appsync/mappingTemplates/adminPasswordConfirm.yml)}

resources:
  # Cognito setup
  - ${file(resources/cognito/cognito-setup.yml)}
  # Cognito auth role
  - ${file(resources/cognito/cognito-auth-role.yml)}
  # Cognito unauth role
  - ${file(resources/cognito/cognito-unauth-role.yml)}
  # Cognito lambda service role
  - ${file(resources/cognito/cognito-lambda-service-role.yml)}

  # ---------- DynamoDb tables ----------
  # services table
  - ${file(resources/db_tables/services-table.yml)}
  # admins table
  - ${file(resources/db_tables/admins-table.yml)}
  # password recovery codes table
  - ${file(resources/db_tables/recovery-codes-table.yml)}