service: BookingApp

plugins:
  #- serverless-appsync-plugin
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1


resources:
  # DynamoDB services table
  - ${file(resources/db_tables/services-table.yml)}
  # Cognito setup
  - ${file(resources/cognito/cognito-setup.yml)}
  # Cognito auth role
  - ${file(resources/cognito/cognito-auth-role.yml)}
  # Cognito unauth role
  - ${file(resources/cognito/cognito-unauth-role.yml)}
  # Cognito lambda service role
  #- ${file(resources/cognito/cognito-lambda-service-role.yml)}