service: BookingApp

plugins:
  #- serverless-appsync-plugin
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1


resources:
  # DynamoDB services table
  - ${file(resources/db_tables/services-table.yml)}