Resources:
  companyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-company
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: adminId
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: adminId-index
          KeySchema:
            - AttributeName: adminId
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL 
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: name-index
          KeySchema:
            - AttributeName: name
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL 
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1