Resources:
  reviewsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-review
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: employeeId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: employeeId-index
          KeySchema:
            - AttributeName: employeeId
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL 
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput: 
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1