Resources:
  servicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-services
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: companyId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: companyId-index
          KeySchema:
            - AttributeName: companyId
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL 
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1